version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "11434:11434"
    environment:
      - API_KEY={{key}}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]